### ISSUE TITLE
关于oauth2-proxy的文章-疑问咨询

### ISSUE THREAD

**Issue by yuhongwei380** [xlabs-club/xlabs-club.github.io#19]
你好，xlabs-clus：
  有幸参阅到你们的这篇文章https://www.xlabs.club/blog/traefik-oauth2-proxy-keycloak/
文章中有一些不解之处，关于oauth2的部分 在keycloak中选择 mapper，我的版本是26.0.1，没有找到  勾选 Add to ID token、Add to access token、Add to token introspection 这部分的内容。
  期待回复~感谢

**Comment by l10178** [comment]
@yuhongwei380 我在博客原文中增加了几张截图，按截图箭头顺序指引就能找到了。

**Comment by yuhongwei380** [comment]
> @yuhongwei380 我在博客原文中增加了几张截图，按截图箭头顺序指引就能找到了。

ok感谢答复，看起来和我之前配置的差不多，不过我遇到了invalid  scope，明天我再按照文章重新配置试试，感谢
